package outbound

type ReviewPublicationRecoveryRepository interface {
	ReviewRunLifecycleRepository
	ReviewPublicationLifecycleRepository
	ReviewPublicationCandidateRepository
	ReviewPublicationInvalidationRepository
}
